name = "Yellow Taxi Goes Vroom"
home = "https://discord.com/channels/731205301247803413/1265482079118950422"
default_url = "https://github.com/soopercool101/Archipelago/releases/download/YTGV.v{{version}}/yellowtaxi.apworld"

[versions]
"0.7.0" = {}
"0.6.1" = {}
"0.6.0" = {}
"0.5.0" = {}
"0.3.2" = {}
